Deploying to gh-pages from  @ 5b68e050e0f5073259fb20b3cd5cbd5cb38f53ac 🚀

diff --git a/dockerfile.html b/dockerfile.html
--- a/dockerfile.html
+++ b/dockerfile.html
@@ -33,8 +33,8 @@
 
 
 
-  <meta content='https://assets.devhints.io/previews/dockerfile.jpg?t=20220603081225' property='og:image'>
-  <meta content='https://assets.devhints.io/previews/dockerfile.jpg?t=20220603081225' property='twitter:image'>
+  <meta content='https://assets.devhints.io/previews/dockerfile.jpg?t=20220609021230' property='og:image'>
+  <meta content='https://assets.devhints.io/previews/dockerfile.jpg?t=20220609021230' property='twitter:image'>
   <meta content='900' property='og:image:width'>
   <meta content='471' property='og:image:height'>
 
@@ -99,11 +99,11 @@ gtag('config','UA-106902774-1');
 <!-- deferred css -->
 <script id='deferred-css'>;(function(links){(requestAnimationFrame||mozRequestAnimationFrame||webkitRequestAnimationFrame||msRequestAnimationFrame||(function(fn){window.addEventListener('load',fn)}))(function(){var h=document.getElementsByTagName('head')[0],l,i;for (i=0;i<links.length;i++){l=document.createElement('link');l.rel='stylesheet';l.href=links[i];h.appendChild(l);}})})([
 'https://fonts.googleapis.com/css?family=Cousine',
-'./assets/2017/style.css?t=20220603081225'
+'./assets/2017/style.css?t=20220609021230'
 ])</script>
 <noscript id='deferred-css-fallback'>
 <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Cousine'>
-<link rel='stylesheet' href='./assets/2017/style.css?t=20220603081225'>
+<link rel='stylesheet' href='./assets/2017/style.css?t=20220609021230'>
 </noscript>
 
 <script type='application/ld+json'>
@@ -115,7 +115,7 @@ gtag('config','UA-106902774-1');
     "@id": "https://google.com/article"
   },
   "headline": "Dockerfile cheatsheet",
-  "image": [ "https://assets.devhints.io/previews/dockerfile.jpg?t=20220603081225" ],
+  "image": [ "https://assets.devhints.io/previews/dockerfile.jpg?t=20220609021230" ],
   "description": "The one-page guide to Dockerfile: usage, examples, links, snippets, and more."
 }
 </script>
@@ -239,6 +239,19 @@ RUN mkdir $APP_HOME
 <pre><code class="language-docker">ADD file.xyz /file.xyz
 COPY --chown=user:group host_file.xyz /path/container_file.xyz
 </code></pre>
+
+<h3 id="run-commands-in-strict-shell">Run commands in strict shell</h3>
+
+<pre><code class="language-docker">ENV my_var
+SHELL ["/bin/bash", "-euo", "pipefail", "-c"]
+
+# With strict mode:
+RUN false # fails build like using &amp;&amp;
+RUN echo "$myvar" # will throw error due to typo
+RUN true | false # will bail out of pipe
+</code></pre>
+
+<p>Using <code>shell</code> will turn on strict mode for shell commands.</p>
 
 <h3 id="onbuild">Onbuild</h3>
 
@@ -568,7 +581,7 @@ function n(n,t,e){n.addEventListener?n.addEventListener(t,e):n.attachEvent("on"+
 },{}],"eoMl":[function(require,module,exports) {
 "use strict";var e=u(require("./wrapify")),d=u(require("dom101/add-class")),t=u(require("dom101/on"));function u(e){return e&&e.__esModule?e:{default:e}}var a,o=document.querySelector("[data-js-main-body]");function r(){a||((0,d.default)(document.documentElement,"LoadDone"),a=!0)}o&&((0,e.default)(o),(0,d.default)(o,"-wrapified")),(0,t.default)(window,"load",r),setTimeout(r,5e3);
 },{"./wrapify":"hE9p","dom101/add-class":"G20n","dom101/on":"DJ2P"}]},{},["eoMl"], null)</script>
-<script src='./assets/packed/app.js?t=20220603081225'></script>
+<script src='./assets/packed/app.js?t=20220609021230'></script>
 <script src='https://cdn.jsdelivr.net/npm/prismjs@1.6.0/components/prism-docker.min.js'></script>
 
 
